# Generated by Django 3.0.7 on 2022-02-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default='1', help_text='Duration of the quiz in seconds'),
        ),
    ]
